import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class ShoesDataService {
  constructor() {}

  allShoes: any[] = [
    {
      id: '1',
      src: '../../../assets/owl carousel/adidas/adidas1.png',
      alt: 'no shoes',
      title: '12',
      price: '40000',
      productName: 'Adidas Kaiser 5 Liga',
    },
    {
      id: '2',
      src: '../../../assets/owl carousel/nike/nike3.png',
      alt: 'no shoes',
      title: '12',
      price: '10000',
      productName: 'Adidas Y-3 Yohji Yamamoto',
    },
    {
      id: '3',
      src: '../../../assets/owl carousel/new balance/nb1.png',
      alt: 'no shoes',
      title: '12',
      price: '880000',
      productName: 'Adidas superstar',
    },
    {
      id: '4',
      src: '../../../assets/owl carousel/nike/nike4.png',
      alt: 'no shoes',
      title: '12',
      price: '10000',
      productName: 'Adidas Black Shoes',
    },
    {
      id: '5',
      src: '../../../assets/owl carousel/new balance/nb2.png',
      alt: 'no shoes',
      title: '12',
      price: '880000',
      productName: 'Adidas superstar',
    },
    {
      id: '6',
      src: '../../../assets/owl carousel/adidas/adidas4.png',
      alt: 'no shoes',
      title: '12',
      price: '10000',
      productName: 'Adidas Black Shoes',
    },
    {
      id: '7',
      src: '../../../assets/owl carousel/nike/nike5.png',
      alt: 'no shoes',
      title: '12',
      price: '35000',
      productName: 'Adidas Campus',
    },
    {
      id: '8',
      src: '../../../assets/owl carousel/new balance/nb3.png',
      alt: 'no shoes',
      title: '12',
      price: '880000',
      productName: 'Adidas superstar',
    },
    {
      id: '9',
      src: '../../../assets/owl carousel/adidas/adidas5.png',
      alt: 'no shoes',
      title: '12',
      price: '35000',
      productName: 'Adidas Campus',
    },
    {
      id: '10',
      src: '../../../assets/owl carousel/new balance/nb4.png',
      alt: 'no shoes',
      title: '12',
      price: '880000',
      productName: 'Adidas superstar',
    },
    {
      id: '11',
      src: '../../../assets/owl carousel/nike/nike2.png',
      alt: 'no shoes',
      title: '12',
      price: '40000',
      productName: 'Adidas Kaiser 5 Liga',
    },
    {
      id: '12',
      src: '../../../assets/owl carousel/new balance/nb5.png',
      alt: 'no shoes',
      title: '12',
      price: '880000',
      productName: 'Adidas superstar',
    },
    {
      id: '13',
      src: '../../../assets/owl carousel/adidas/adidas6.png',
      alt: 'no shoes',
      title: '12',
      price: '50000',
      productName: 'Adidas blue shoes',
    },
    {
      id: '14',
      src: '../../../assets/owl carousel/new balance/nb6.png',
      alt: 'no shoes',
      title: '12',
      price: '880000',
      productName: 'Adidas superstar',
    },
    {
      id: '15',
      src: '../../../assets/owl carousel/adidas/adidas7.png',
      alt: 'no shoes',
      title: '12',
      price: '880000',
      productName: 'Adidas superstar',
    },
    {
      id: '16',
      src: '../../../assets/owl carousel/nike/nike7.png',
      alt: 'no shoes',
      title: '12',
      price: '880000',
      productName: 'Adidas superstar',
    },
    {
      id: '17',
      src: '../../../assets/owl carousel/nike/nike1.png',
      alt: 'no shoes',
      title: '12',
      price: '40000',
      productName: 'Adidas Kaiser 5 Liga',
    },
    {
      id: '18',
      src: '../../../assets/owl carousel/nike/nike8.png',
      alt: 'no shoes',
      title: '12',
      price: '520000',
      productName: 'Adidas High Ankle',
    },
    {
      id: '19',
      src: '../../../assets/owl carousel/adidas/adidas8.png',
      alt: 'no shoes',
      title: '12',
      price: '520000',
      productName: 'Adidas High Ankle',
    },
    {
      id: '20',
      src: '../../../assets/owl carousel/nike/nike6.png',
      alt: 'no shoes',
      title: '12',
      price: '50000',
      productName: 'Adidas blue shoes',
    }
  ];
  

  adidas: any[] = [
    {
      id: '',
      src: '../../../assets/owl carousel/adidas/adidas1.png',
      alt: 'no shoes',
      title: '12',
      price: '40000',
      productName: 'Adidas Kaiser 5 Liga',
    },
    {
      id: '2',
      src: '../../../assets/owl carousel/adidas/adidas2.png',
      alt: 'no shoes',
      title: '12',
      price: '20000',
      productName: 'Adidas Samba OG',
    },
    {
      id: '3',
      src: '../../../assets/owl carousel/adidas/adidas3.png',
      alt: 'no shoes',
      title: '12',
      price: '10000',
      productName: 'Adidas Y-3 Yohji Yamamoto',
    },
    {
      id: '4',
      src: '../../../assets/owl carousel/adidas/adidas4.png',
      alt: 'no shoes',
      title: '12',
      price: '10000',
      productName: 'Adidas Black Shoes',
    },
    {
      id: '5',
      src: '../../../assets/owl carousel/adidas/adidas5.png',
      alt: 'no shoes',
      title: '12',
      price: '35000',
      productName: 'Adidas Campus',
    },
    {
      id: '6',
      src: '../../../assets/owl carousel/adidas/adidas6.png',
      alt: 'no shoes',
      title: '12',
      price: '50000',
      productName: 'Adidas blue shoes',
    },
    {
      id: '7',
      src: '../../../assets/owl carousel/adidas/adidas7.png',
      alt: 'no shoes',
      title: '12',
      price: '880000',
      productName: 'Adidas superstar',
    },
    {
      id: '8',
      src: '../../../assets/owl carousel/adidas/adidas8.png',
      alt: 'no shoes',
      title: '12',
      price: '520000',
      productName: 'Adidas High Ankle',
    },
  ];

  nike: any[] = [
    {
      id: '1',
      src: '../../../assets/owl carousel/nike/nike1.png',
      alt: 'no shoes',
      title: '12',
      price: '40000',
      productName: 'Adidas Kaiser 5 Liga',
    },
    {
      id: '2',
      src: '../../../assets/owl carousel/nike/nike2.png',
      alt: 'no shoes',
      title: '12',
      price: '40000',
      productName: 'Adidas Kaiser 5 Liga',
    },
    {
      id: '3',
      src: '../../../assets/owl carousel/nike/nike3.png',
      alt: 'no shoes',
      title: '12',
      price: '10000',
      productName: 'Adidas Y-3 Yohji Yamamoto',
    },
    {
      id: '4',
      src: '../../../assets/owl carousel/nike/nike4.png',
      alt: 'no shoes',
      title: '12',
      price: '10000',
      productName: 'Adidas Black Shoes',
    },
    {
      id: '5',
      src: '../../../assets/owl carousel/nike/nike5.png',
      alt: 'no shoes',
      title: '12',
      price: '35000',
      productName: 'Adidas Campus',
    },
    {
      id: '6',
      src: '../../../assets/owl carousel/nike/nike6.png',
      alt: 'no shoes',
      title: '12',
      price: '50000',
      productName: 'Adidas blue shoes',
    },
    {
      id: '7',
      src: '../../../assets/owl carousel/nike/nike7.png',
      alt: 'no shoes',
      title: '12',
      price: '880000',
      productName: 'Adidas superstar',
    },
    {
      id: '8',
      src: '../../../assets/owl carousel/nike/nike8.png',
      alt: 'no shoes',
      title: '12',
      price: '520000',
      productName: 'Adidas High Ankle',
    },
  ];

  newbalance: any[] = [
    {
      id: '1',
      src: '../../../assets/owl carousel/new balance/nb1.png',
      alt: 'no shoes',
      title: '12',
      price: '880000',
      productName: 'Adidas superstar',
    },
    {
      id: '2',
      src: '../../../assets/owl carousel/new balance/nb2.png',
      alt: 'no shoes',
      title: '12',
      price: '880000',
      productName: 'Adidas superstar',
    },
    {
      id: '3',
      src: '../../../assets/owl carousel/new balance/nb3.png',
      alt: 'no shoes',
      title: '12',
      price: '880000',
      productName: 'Adidas superstar',
    },
    {
      id: '4',
      src: '../../../assets/owl carousel/new balance/nb4.png',
      alt: 'no shoes',
      title: '12',
      price: '880000',
      productName: 'Adidas superstar',
    },
    {
      id: '5',
      src: '../../../assets/owl carousel/new balance/nb5.png',
      alt: 'no shoes',
      title: '12',
      price: '880000',
      productName: 'Adidas superstar',
    },
    {
      id: '6',
      src: '../../../assets/owl carousel/new balance/nb6.png',
      alt: 'no shoes',
      title: '12',
      price: '880000',
      productName: 'Adidas superstar',
    },
  ];
}
